### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by LizIsTired** [LizIsTired/StarminerRecrafted#2]
- [ ] Add star generation
- [ ] Add placeholder items/blocks/entities
- [ ] Make gravity change according to gravity fields
- [x] Add placeholder dimension

These things need to be completed before I release the first beta.
Will bring mod version to 0.1.0.

**Comment by LizIsTired** [comment]
Star generation is annoying but it's top priority right now, I've already added most placeholder items/blocks/entities, done *some* work on gravity "shifting" and added a dimension but am no further in terms of getting stars to generate.

**Comment by LizIsTired** [comment]
The main issue with star generation is finding a way to create blocky spheres, looking at the source for MiniHUD helps, I might look into WorldEdit at some point to see how it does it. After that I need to work on actually getting structures to generate; something that's been massively annoying to do up to this point.

**Comment by LizIsTired** [comment]
Ok! I got the spheres to generate! Now to make them structures and work on the randomness...

**Comment by LizIsTired** [comment]
Improved sphere generation with new algorithm, I do need to work on it further though, currently the sphere spawns at 0,0,0 instead of at the block. Still no further work done on randomness and structures.
