### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by LizIsTired** [LizIsTired/StarminerRecrafted#3]
- [ ] Add config reading/writing
- [ ] Give behaviour to crucial items/blocks/entities
- [ ] Refine dimension (won't be fully done by milestone 2)
- [ ] Add biome specific stars

Will need to be done before I release beta 2.
Will bring mod version to 0.2.0.

**Comment by LizIsTired** [comment]
I'll be using cloth config for config reading and writing, seems to work for most other mods.

Adding behaviour to items would include: 

- [ ] Gravity Controller
- [ ] Star Controller
- [ ] Solar Wind Fan
- [ ] G-rapple Gun
- [ ] Floating Block Gun

Adding behaviour to blocks would include:

- [ ] Gravity Core
- [ ] Man Bazooka
- [ ] Navigator
- [ ] Gravity Wall
- [ ] Fake Rotator
- [ ] Chest
- [ ] Star Bed

Refining the dimension would include:

- [ ] Adding star generation to dimension (including star rings)
- [ ] Add no gravity and drag on dimension enter
- [ ] Sort out dimension "effects" using datapacks (need to fix: clouds, skybox, fog)
- [ ] Need to add planar earth effect 
- [ ] Auto add and remove from dimension based on player height
